### The information below is common to Questions 1 to 5

Note : 
* Shape of the dataset is (9450,13) [Note if you are not getting this shape that means your data has not been uploaded correctly to the collab 

*    The target feature in the dataset is the 'Price' column. 

*    Random state should be taken as 42 wherever applicable. 
    
*    ignore all the warnings while executing the codes.


### Metadata

1. **Airline:** The name of the airline.

2. **Source:** The source from which the journey begins.

3. **Destination:** The destination where the journey ends.

4. **Route:** The route taken by the flight.

5. **Dep_Time:** The time when the journey starts from the source.

6. **Arrival_Time:** The time of arrival at the destination.

7. **Duration:** The total duration of the flight.

8. **Total_Stops:** The total number of stops between the source and destination.

9. **Additional_Info:** Additional information about the flight.

10. **Price:** The price of the flight ticket. **Target Variable**

11. **Month:** The month in which the journey takes place.

12. **WeekDay:** The day of the week on which the journey starts.

13. **Day:** The date of the journey.



## Dataset

[**Click here to view the dataset**](https://drive.google.com/file/d/1zP38WCdZQ9StsAHTTLk72763QJQkhWrG/view)



Revise Question : 2 ,3

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('Preprocessing1.csv')

In [ ]:
data.head(4)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0

In [184]:
data.shape

(9450, 13)

In [126]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9450 entries, 0 to 9449
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          9450 non-null   str
 1   Source           9450 non-null   str
 2   Destination      9450 non-null   str
 3   Route            9449 non-null   str
 4   Dep_Time         9450 non-null   str
 5   Arrival_Time     9450 non-null   str
 6   Duration         9450 non-null   str
 7   Total_Stops      9250 non-null   str
 8   Additional_Info  9450 non-null   str
 9   Price            9450 non-null   int64
 10  Month            9450 non-null   int64
 11  WeekDay          9450 non-null   str
 12  Day              9214 non-null   float64
dtypes: float64(1), int64(2), str(10)
memory usage: 959.9 KB

In [127]:
data.describe()

              Price        Month          Day
count   9450.000000  9450.000000  9214.000000
mean    9027.895556     4.718730    13.517582
std     4466.677471     1.162725     8.459792
min     1759.000000     3.000000     1.000000
25%     5198.000000     3.000000     6.000000
50%     8366.000000     5.000000    12.000000
75%    12373.000000     6.000000    21.000000
max    57209.000000     6.000000    27.000000

##### Q1 : What is the average of the flight ticket price? Write your answer correct to two decimal places.

In [128]:
data['Price'].mean().round(2)

np.float64(9027.9)

##### Q2 : During which month did the highest number of flights occur? Months are represented by numerical codes, with January corresponding to 1, February to 2, and so forth.

In [129]:
data['Month'].value_counts(ascending=False)  # all values

data['Month'].value_counts().idxmax()   # id

np.int64(5)

##### Q3 : Is the average price of flight tickets higher on weekends (Saturday and Sunday) or on weekdays (Remaining 5 days)?

In [ ]:
avg = data['Price'].mean()
weekend_avg = data[data['WeekDay'].isin(['Saturday' , 'Sunday'])]['Price'].mean()
weekday_avg = data[~data['WeekDay'].isin(['Saturday' , 'Sunday'])]['Price'].mean()

print(f"The avg ticket price is {avg}, Avg of ticket price on weekend is {weekend_avg} and Price of ticket on weekdays is {weekday_avg}")

if weekend_avg > avg : 
    print("On Weekend Ticket price is higher than normal days")
else : 
    print("On Normal days Ticket price is higher than Weekend days")

The avg ticket price is 9027.895555555555, Avg of ticket price on weekend is 9058.016077170418 and Price of ticket on weekdays is 9015.219666215608
On Weekend Ticket price is higher than normal days

In [137]:
# avg_price
# weekDay_avg = data.groupby('WeekDay')['Price'].mean()
# avg_price = data['Price'].mean()
# 


# data['WeekDay'].value_counts().reset_index().sort_index(ascending=True)
# for i in weekDay_avg : 
    # if i > avg_price :
        # print(True)
    # else : 
        # print(False)
        


# for i in weekDay_avg :
    # print(i)




# data.drop(columns='weekDay_avg')


# data.groupby('WeekDay')['Price'].mean()
# type(data.groupby('WeekDay')['Price'].mean())


# type(data['Price'].mean())

##### Q4 : Two of the entries in the 'Additional_Info' column are 'No info' and 'No Info'. Replace all occurrences of 'No Info' with 'No info'. How many flights fall under airline 'IndiGo' and have 'No info' as additional information?

In [ ]:
data['Additional_Info'] = data['Additional_Info'].replace('No Info', 'No info')


# checking "No Info exist or not "
# data[data['Additional_Info'] == 'No Info']
# data[data['Additional_Info'] == 'No info']


con1 = (data['Airline'] == 'IndiGo') & (data['Additional_Info'] == 'No info')

data[con1].shape

data[con1].shape[0]

1650

In [186]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9450 entries, 0 to 9449
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          9450 non-null   str
 1   Source           9450 non-null   str
 2   Destination      9450 non-null   str
 3   Route            9449 non-null   str
 4   Dep_Time         9450 non-null   str
 5   Arrival_Time     9450 non-null   str
 6   Duration         9450 non-null   str
 7   Total_Stops      9250 non-null   str
 8   Additional_Info  9450 non-null   str
 9   Price            9450 non-null   int64
 10  Month            9450 non-null   int64
 11  WeekDay          9450 non-null   str
 12  Day              9214 non-null   float64
dtypes: float64(1), int64(2), str(10)
memory usage: 959.9 KB

##### Q5 : Convert the values of 'Duration' into seconds. Enter the average duration (in seconds) of a flight. Enter your answer correct to two decimal places.

In [209]:
# data['Duration']

def convert_to_seconds(duration):
    parts = duration.split()
    
    hours = 0
    minutes = 0
    
    for part in parts:
        if 'h' in part:
            hours = int(part.replace('h', ''))
        elif 'm' in part:
            minutes = int(part.replace('m', ''))
    
    seconds = hours * 3600 + minutes * 60
    
    return seconds


data['Duration']

# data['Duration'].apply(convert_to_seconds)
data['Duration'].apply(convert_to_seconds).mean().round(2)

np.float64(38957.94)

#### The information below is common to Questions 6 to 7


#### Apply the following functions to the columns Dep_Time and Arrival_Time:

* 1. Transform the values in the 'dep_time' and 'arrival_time' columns to represent the hour component. For instance, if an entry is 10:05 June 13 or 10:05, the corresponding value should be 10. 

* 2. Then convert the time into four categories as follows:
    ```
    1. 5 <= hour < 12 = Morning 
    2. 12 <= hour < 17 = Afternoon 
    3. 17 <= hour < 20 = Evening 
    4. 20 <= hour < 5 = Night
    
    ```

Note: Please ensure that you make the changes directly within the dataset and continue to use that modified dataset for subsequent questions.

##### Q6 : How many flights started in the Morning and arrived the destination at Evening?

In [6]:
# data[['Dep_Time' , 'Arrival_Time']]

def get_hour(time):
    return int(time.split(':')[0])

con1 = (data['Dep_Time'].apply(get_hour) < 12) & (data['Dep_Time'].apply(get_hour) >= 5) & (data['Arrival_Time'].apply(get_hour) >=17 ) & (data['Arrival_Time'].apply(get_hour) < 20 )

print(data[con1].shape[0])

922

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('Preprocessing1.csv')


# Function to extract hour
def get_hour(time):
    return int(time.split(':')[0])


# Function to convert hour into category
def time_category(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 20:
        return 'Evening'
    else:
        return 'Night'


# Convert Dep_Time and Arrival_Time into hours
df['Dep_Time'] = df['Dep_Time'].apply(get_hour)
df['Arrival_Time'] = df['Arrival_Time'].apply(get_hour)


# Convert hours into time categories
df['Dep_Time'] = df['Dep_Time'].apply(time_category)
df['Arrival_Time'] = df['Arrival_Time'].apply(time_category)


# Save the modified DataFrame permanently
# df.to_csv('Preprocessing1.csv', index=False)


# Check the result
# print(df[['Dep_Time', 'Arrival_Time']].head())

    Dep_Time Arrival_Time
0      Night        Night
1  Afternoon      Evening
2    Evening        Night
3    Evening        Night
4    Evening      Evening

##### Q7 : Encode the values of column 'WeekDay' as follows: Weekends (Sunday, Saturday) = 1 all remaining five days = 0  . What is the most frequent (mode) WeekDay?

In [20]:
# Weekend = 1, Weekday = 0

data['WeekDay'] = data['WeekDay'].apply(lambda x: 1 if x in ['Saturday', 'Sunday'] else 0)

data



# # Finding the mode
print(data['WeekDay'].mode())




# con1 = data['WeekDay'].isin(['Sunday','Saturday'])
# data[con1] 

# data['WeekDay'] = 1

0    0
Name: WeekDay, dtype: int64

# Week 1 : PA (Imp Topics)

> Dataset used: Flight Price data (`Preprocessing1.csv`), target = `Price`
> Convention: `df` / `data` = DataFrame, `'col'` = column name

---

## 1. Importing Libraries & Loading Data

**Concept:** `pandas` is the main library for tabular data. A **DataFrame** is a 2D table (rows = records, columns = features). A single column is a **Series**.

```python
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')   # ignore warnings

data = pd.read_csv('Preprocessing1.csv')   # load CSV into DataFrame
```

---

## 2. Inspecting a DataFrame

| Syntax | Purpose |
|---|---|
| `data.head(n)` | First n rows (default 5) |
| `data.tail(n)` | Last n rows |
| `data.shape` | (rows, columns) tuple |
| `data.info()` | Column names, dtypes, non-null counts, memory |
| `data.describe()` | Count, mean, std, min, quartiles, max (numeric cols) |
| `data.columns` | List of column names |
| `data.dtypes` | Data type of each column |
| `data.isnull().sum()` | Missing values per column |

```python
data.head(4)
data.shape          # (9450, 13)
data.info()
data.describe()
```

---

## 3. Selecting Columns

```python
data['Price']                    # single column  -> Series
data[['Airline', 'Price']]       # multiple columns -> DataFrame (note double [[ ]])
```

---

## 4. Basic Statistics

```python
data['Price'].mean()      # average
data['Price'].median()    # middle value
data['Price'].min()
data['Price'].max()
data['Price'].sum()
data['Price'].count()     # non-null count
data['WeekDay'].mode()    # most frequent value(s) -> returns a Series
data['Price'].mean().round(2)   # round to 2 decimals
```

**Concept:** `mode()` returns a Series (there can be ties); use `.mode()[0]` for the first value.

---

## 5. Frequency Analysis – `value_counts()`

**Concept:** Counts how many times each unique value appears, sorted high → low by default.

```python
data['Month'].value_counts()                    # counts per month
data['Month'].value_counts(ascending=True)      # low -> high
data['Month'].value_counts(normalize=True)      # proportions instead of counts
data['Month'].value_counts().idxmax()           # the VALUE (label) with highest count
data['Month'].value_counts().max()              # the highest COUNT itself
```

**`max()` vs `idxmax()`:**
- `max()` → the largest number (e.g., 2500 flights)
- `idxmax()` → the label of that largest number (e.g., month 5)

---

## 6. Boolean Filtering (Row Selection)

**Concept:** A condition produces a True/False Series (a *mask*). Passing the mask inside `df[...]` keeps only rows where it is True.

**Comparison operators:** `==`, `!=`, `>`, `<`, `>=`, `<=`

```python
data[data['Price'] > 10000]                 # price above 10000
data[data['Airline'] == 'IndiGo']           # only IndiGo
data[data['Airline'] != 'IndiGo']           # everything except IndiGo
data[data['Airline'] == 'IndiGo'].shape[0]  # COUNT of filtered rows
```

> `shape` → (rows, cols), `shape[0]` → number of rows only.

---

## 7. Multiple Conditions

| Operator | Meaning |
|---|---|
| `&` | AND (both must be true) |
| `\|` | OR (at least one true) |
| `~` | NOT (invert) |

⚠️ Always wrap each condition in **parentheses**. Do not use Python's `and` / `or` / `not` with Series.

```python
cond = (data['Airline'] == 'IndiGo') & (data['Additional_Info'] == 'No info')
data[cond].shape[0]

data[(data['Price'] > 5000) | (data['Total_Stops'] == 'non-stop')]
```

---

## 8. `isin()` – Match Against a List

**Concept:** Checks if each value is present in a given list. Cleaner than chaining many `|` conditions.

```python
data[data['WeekDay'].isin(['Saturday', 'Sunday'])]      # weekend rows
data[~data['WeekDay'].isin(['Saturday', 'Sunday'])]     # weekday rows (~ = NOT)
```

Weekend vs weekday average price:
```python
weekend_avg = data[data['WeekDay'].isin(['Saturday','Sunday'])]['Price'].mean()
weekday_avg = data[~data['WeekDay'].isin(['Saturday','Sunday'])]['Price'].mean()

if weekend_avg > weekday_avg:
    print("Weekend tickets are costlier")
else:
    print("Weekday tickets are costlier")
```

---

## 9. `groupby()` (Comparing Groups)

**Concept:** Split data into groups, then aggregate each group.

```python
data.groupby('WeekDay')['Price'].mean()          # avg price per weekday
data.groupby('Airline')['Price'].agg(['mean', 'min', 'max', 'count'])
```

---

## 10. Replacing Values (Data Cleaning)

**Concept:** Fix inconsistent labels (e.g., `'No Info'` vs `'No info'`) so they count as one category.

```python
data['Additional_Info'] = data['Additional_Info'].replace('No Info', 'No info')

# multiple replacements using a dictionary
data['Additional_Info'] = data['Additional_Info'].replace({'No Info': 'No info', 'In-flight meal not included': 'No meal'})
```

> `replace()` returns a new Series. You must **assign it back** (`data['col'] = ...`) to save the change.

---

## 11. Creating / Modifying Columns

```python
data['New_Col'] = 0                               # constant value
data['Price_k'] = data['Price'] / 1000            # from an existing column
data['Price'] = data['Price'] * 1.1               # modify existing column
data['Total'] = data['Price'] + data['Tax']       # from two columns
```

---

## 12. Python Functions (`def`)

**Concept:** A reusable block of code. It takes **parameters**, does work, and `return`s a result.

```python
def function_name(parameter):
    # logic
    return result

def get_hour(time):
    return int(time.split(':')[0])

get_hour('10:05')     # -> 10
```

---

## 13. `apply()` – Run a Function on Every Value

**Concept:** `Series.apply(func)` passes each element to `func` and collects the results into a new Series.

```python
data['Dep_Time'] = data['Dep_Time'].apply(get_hour)
```
> Pass the function **name without parentheses** (`get_hour`, not `get_hour()`).

---

## 14. Lambda Functions

**Concept:** A one-line anonymous function. Best for short logic used with `apply()`.

```python
lambda x: expression
# equivalent to: def f(x): return expression
```

```python
# Simple
data['Price_k'] = data['Price'].apply(lambda x: x / 1000)

# Conditional (if-else inside lambda)
data['WeekDay'] = data['WeekDay'].apply(lambda x: 1 if x in ['Saturday', 'Sunday'] else 0)
```

**Pattern:** `lambda x: value_if_true if condition else value_if_false`

---

## 15. String Manipulation

| Syntax | Purpose | Example |
|---|---|---|
| `s.split()` | Split on whitespace → list | `'2h 50m'.split()` → `['2h','50m']` |
| `s.split(':')` | Split on a delimiter | `'10:05'.split(':')` → `['10','05']` |
| `s.replace('h','')` | Replace text | `'2h'.replace('h','')` → `'2'` |
| `int(s)` | String → integer | `int('2')` → `2` |
| `s.strip()` | Remove surrounding spaces | |
| `'x' in s` | Substring check | `'h' in '2h'` → `True` |

Indexing a list: `parts[0]` first item, `parts[-1]` last item.

---

## 16. Time Processing (Dep_Time / Arrival_Time)

**Step 1 – extract hour:**
```python
def get_hour(time):
    return int(time.split(':')[0])
```
> For values like `'10:05 13 June'`, `split(':')[0]` still gives `'10'`.

**Step 2 – hour → category:**
```python
def time_category(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 20:
        return 'Evening'
    else:                       # 20 to 4
        return 'Night'

data['Dep_Time']     = data['Dep_Time'].apply(get_hour).apply(time_category)
data['Arrival_Time'] = data['Arrival_Time'].apply(get_hour).apply(time_category)
```

**Count Morning → Evening flights:**
```python
data[(data['Dep_Time'] == 'Morning') & (data['Arrival_Time'] == 'Evening')].shape[0]
```

> **Note:** "Night" covers `hour >= 20` or `hour < 5`, so a plain `else` handles it.

---

## 17. Duration Processing

**Concept:** Strings like `'2h 50m'`, `'3h'`, `'45m'` → convert to numeric seconds.
`seconds = hours × 3600 + minutes × 60`

```python
def convert_to_seconds(duration):
    hours = 0
    minutes = 0
    for part in duration.split():
        if 'h' in part:
            hours = int(part.replace('h', ''))
        elif 'm' in part:
            minutes = int(part.replace('m', ''))
    return hours * 3600 + minutes * 60

data['Duration'] = data['Duration'].apply(convert_to_seconds)
data['Duration'].mean().round(2)
```

> Initialising `hours = 0` and `minutes = 0` handles entries that have only one part (e.g., `'3h'`).

---

## 18. Categorical Encoding

**Concept:** Models need numbers, so convert text categories to numeric codes.

```python
# Binary encoding with lambda
data['WeekDay'] = data['WeekDay'].apply(lambda x: 1 if x in ['Saturday', 'Sunday'] else 0)

# Using map() with a dictionary
data['Total_Stops'] = data['Total_Stops'].map({'non-stop': 0, '1 stop': 1, '2 stops': 2})

data['WeekDay'].mode()     # most frequent encoded value
```

---

## 19. Basic EDA Workflow

```
Load Dataset → Inspect (head/shape/info/describe) → Select Columns
→ Filter Rows → Count Values → Calculate Statistics → Clean Values
→ Create/Modify Columns → Apply Functions → Transform Data
```

---

## 20. Quick Cheat Sheet

```python
df['col'].mean()                                   # average
df['col'].value_counts()                           # frequency table
df['col'].value_counts().idxmax()                  # most frequent value
df[df['col'] == 'x']                               # filter
df[df['col'].isin(['A', 'B'])]                     # filter by list
df[~df['col'].isin(['A', 'B'])]                    # exclude list
df[(df['A'] == 'x') & (df['B'] == 'y')]            # AND condition
df['col'] = df['col'].replace('old', 'new')        # replace
df['col'] = df['col'].apply(func)                  # apply function
df['col'] = df['col'].apply(lambda x: 1 if cond else 0)   # lambda encoding
df[cond].shape[0]                                  # count of filtered rows
```

---

## 21. Common Mistakes to Avoid

1. Using `and` / `or` instead of `&` / `|` on Series.
2. Forgetting parentheses around each condition.
3. Forgetting to assign back after `replace()` or `apply()`.
4. Writing `apply(func())` instead of `apply(func)`.
5. Confusing `max()` (the count) with `idxmax()` (the label).
6. Using `[ ]` instead of `[[ ]]` when selecting multiple columns.
7. Re-running a conversion cell twice (e.g., `get_hour` on an already converted column causes an error).